# Generated by Django 5.1.3 on 2024-12-24 12:15

import tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=tools.models.generate_order_id, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('salesperson_name', models.CharField(max_length=255)),
                ('required_design', models.ImageField(upload_to='designs/')),
                ('product_list', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
            ],
        ),
    ]
