# Generated by Django 5.1.3 on 2024-12-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_design',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
