# Generated by Django 5.1.3 on 2024-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_order_product_list_alter_order_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='required_design',
            new_name='back_design',
        ),
        migrations.AddField(
            model_name='order',
            name='front_design',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='pocket_design',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='sleeve_design',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
