# Generated by Django 5.1.3 on 2024-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_rename_required_design_order_back_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_Size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
