# Generated by Django 5.1.3 on 2024-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_order_design_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_Size',
            field=models.CharField(default='Size not given', max_length=255),
        ),
    ]
