# Generated by Django 5.1.3 on 2024-12-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_alter_order_design_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_Size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
